var MESSAGE_WINDOW_ID="messageWindow";var PROGRESS_METER_ID="progressMeterWindow";var PROGRESS_METER_ACTIVE_CELLS=20;var PROGRESS_METER_CELLS=70;var PROGRESS_METER_WAIT=40;var progressMeterCellIndex=PROGRESS_METER_CELLS;var progressMeterColor=null;var progressMeterRunning=false;
function closeMessageWindow(windowId){divId=MESSAGE_WINDOW_ID;if(windowId)divId=windowId;var divToClose=document.getElementById(divId);if(divToClose==null&&divId!=PROGRESS_METER_ID)divToClose=document.getElementById(MESSAGE_WINDOW_ID);if(divToClose!=null){$("#"+divId).stop(false,false).stop(false,false);$("#"+divId).animate({opacity:1});divToClose.style.width=0;divToClose.style.display="none"}if(document.forms[0]!=null)setDefaultFocus(document.forms[0]);if(progressMeterRunning){progressMeterRunning=
false;setDetailButtonSet()}}function fadeHex(startColor,endColor,ratio){var r=startColor>>16;var g=startColor>>8&255;var b=startColor&255;r+=((endColor>>16)-r)*ratio;g+=((endColor>>8&255)-g)*ratio;b+=((endColor&255)-b)*ratio;return"#"+(r<<16|g<<8|b).toString(16).pad("0",6,true)}
function getMessageWindowHTML(messageText,error,extraInfo,extraInfoHeight,width){var icon='\x3ci class\x3d"fa fa-check fa-4x" style\x3d"color:#6dad69"/\x3e';if(error)icon='\x3ci class\x3d"fa fa-times fa-4x" style\x3d"color:#cb2428"/\x3e';var html=getCommonMessageBoxHTML(icon,error?"errorMessageH1":"messageBoxH1",messageText,extraInfo);var buttonResourceID="button.ok";var buttonIcon=getButtonFontIconHTML(buttonResourceID);html+="\x3ctr\x3e"+'\x3ctd colspan\x3d"2" align\x3d"center"\x3e'+'\x3cbutton style\x3d"margin-left: 10px;" type\x3d"button" class\x3d"button" id\x3d"closeButton" tabindex\x3d"0" name\x3d"closeButton" onclick\x3d"closeMessageWindow();"\x3e'+
buttonIcon+'\x26nbsp;\x3cspan class\x3d"button-text"\x3e'+grabResource(buttonResourceID)+"\x3c/span\x3e\x3c/button\x3e"+"\x3c/td\x3e"+"\x3c/tr\x3e"+"\x3c/table\x3e";return html}
function getCommonMessageBoxHTML(icon,headerBarStyle,messageText,extraInfo){var html='\x3ctable width\x3d"100%" cellpadding\x3d"4" cellspacing\x3d"0" border\x3d"0"\x3e'+'\x3ctr\x3e\x3ctd colspan\x3d"2" style\x3d"padding: 0px;"\x3e \x3ch1 class\x3d"'+headerBarStyle+'"\x3e\x3c/h1\x3e \x3c/td\x3e\x3c/tr\x3e'+"\x3ctr\x3e"+'\x3ctd colspan\x3d"2"\x3e'+'\x3cimg src\x3d"images/spacer.gif" height\x3d"5" alt\x3d" "\x3e'+"\x3c/td\x3e"+"\x3c/tr\x3e"+'\x3ctr valign\x3d"middle"  \x3e'+'\x3ctd width\x3d"1" valign\x3d"top" style\x3d"padding-left:15px"\x3e'+
icon+"\x3c/td\x3e"+'\x3ctd width\x3d"*" valign\x3d"middle"\x3e'+'\x3cdiv tabindex\x3d"0" class\x3d"messageText"\x3e'+messageText+"\x3c/div\x3e"+"\x3c/td\x3e"+"\x3c/tr\x3e"+"\x3ctr\x3e"+'\x3ctd colspan\x3d"2"\x3e'+'\x3cimg src\x3d"images/spacer.gif" height\x3d"5" alt\x3d" "\x3e'+"\x3c/td\x3e"+"\x3c/tr\x3e";if(extraInfo!=null)html+="\x3ctr\x3e"+'\x3ctd colspan\x3d"2"\x3e'+'\x3chr class\x3d"horizontalRule messageRule"\x3e'+"\x3c/td\x3e"+"\x3c/tr\x3e"+"\x3ctr\x3e"+'\x3ctd colspan\x3d"2"  align\x3d"center"\x3e\x3ctextarea class\x3d"messageExtraInfo" rows\x3d"10" readonly\x3e'+
extraInfo+"\x3c/textarea\x3e\x3c/td\x3e"+"\x3c/tr\x3e"+"\x3ctr\x3e"+'\x3ctd colspan\x3d"2"\x3e\x3cimg src\x3d"images/spacer.gif" height\x3d"5" alt\x3d" "\x3e\x3c/td\x3e'+"\x3c/tr\x3e";return html}function getProgressMeterCell(index){var indexToGet=progressMeterCellIndex+index;if(indexToGet>PROGRESS_METER_CELLS)indexToGet=indexToGet-PROGRESS_METER_CELLS;return document.getElementById("meterCell"+indexToGet)}
function getProgressMeterHTML(messageText){var progressMessage=messageText;if(progressMessage==null)progressMessage=grabResource("message.progressMeter.defaultMessage");var html='\x3cdiv id\x3d"progressMessage" class\x3d"messageText c3Color" style\x3d"padding-top:10px; text-align: center"\x3e'+progressMessage+"\x3c/div\x3e"+'\x3cdiv style\x3d"padding-bottom: 10px; padding-top: 15px;" \x3e'+"\x3ccenter\x3e"+'\x3ctable border\x3d"0" cellpadding\x3d"0" cellspacing\x3d"0"\x3e'+"\x3ctr\x3e";for(var i=
1;i<=PROGRESS_METER_CELLS;i++){var borderStyle="border-top: solid black 1px; border-bottom: solid black 1px";if(i==1)borderStyle+="; border-left: solid black 1px;";else if(i==PROGRESS_METER_CELLS)borderStyle+="; border-right: solid black 1px;";html+='\x3ctd id\x3d"meterCell'+i+'" style\x3d"'+borderStyle+'"\x3e\x3cimg src\x3d"images/spacer.gif" height\x3d"15" width\x3d"4" alt\x3d" "\x3e\x3c/td\x3e'}html+="\x3c/tr\x3e"+"\x3c/table\x3e"+"\x3c/center\x3e"+"\x3c/div\x3e";return html}
function getPromptWindowHTML(messageText,icon,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action,extraInfo){var html=getCommonMessageBoxHTML(icon,"warningMessageH1",messageText,extraInfo);html+="\x3ctr\x3e"+'\x3ctd colspan\x3d"2" align\x3d"center"\x3e'+'\x3ctable border\x3d"0" cellpadding\x3d"0" cellspacing\x3d"0"\x3e'+"\x3ctr\x3e";if(button1Action==null)button1Action="";var button1Icon=getButtonFontIconHTML(button1Label);html+="\x3ctd\x3e"+'\x3cbutton type\x3d"button" class\x3d"button" id\x3d"msgbutton1" tabindex\x3d"0" name\x3d"closeButton" onclick\x3d"closeMessageWindow(\'promptWindow\');EmbeddedPopup.popupManager.closeCover();EmbeddedPopup.popupManager.openedCoversForMessageWindow--;'+
button1Action+'"\x3e'+button1Icon+'\x26nbsp;\x3cspan class\x3d"button-text"\x3e'+grabResource(button1Label)+"\x3c/span\x3e\x3c/button\x3e"+"\x3c/td\x3e";if(button2Label!=null){var button2Icon=getButtonFontIconHTML(button2Label);if(button2Action==null)button2Action="";html+="\x3ctd\x3e"+'\x3cimg src\x3d"images/spacer.gif" width\x3d"2" alt\x3d" "\x3e'+"\x3c/td\x3e"+"\x3ctd\x3e"+'\x3cbutton type\x3d"button" class\x3d"button" tabindex\x3d"1" name\x3d"closeButton" onclick\x3d"closeMessageWindow(\'promptWindow\');EmbeddedPopup.popupManager.closeCover();EmbeddedPopup.popupManager.openedCoversForMessageWindow--;'+
button2Action+'"\x3e'+button2Icon+'\x26nbsp;\x3cspan class\x3d"button-text"\x3e'+grabResource(button2Label)+"\x3c/span\x3e\x3c/button\x3e"+"\x3c/td\x3e"}if(button3Label!=null){var button3Icon=getButtonFontIconHTML(button3Label);if(button3Action==null)button3Action="";html+="\x3ctd\x3e"+'\x3cimg src\x3d"images/spacer.gif" width\x3d"2" alt\x3d" "\x3e'+"\x3c/td\x3e"+"\x3ctd\x3e"+'\x3cbutton type\x3d"button" class\x3d"button" tabindex\x3d"2" name\x3d"closeButton" onclick\x3d"closeMessageWindow(\'promptWindow\');EmbeddedPopup.popupManager.closeCover();EmbeddedPopup.popupManager.openedCoversForMessageWindow--;'+
button3Action+'"\x3e'+button3Icon+'\x26nbsp;\x3cspan class\x3d"button-text"\x3e'+grabResource(button3Label)+"\x3c/span\x3e\x3c/button\x3e"+"\x3c/td\x3e"}html+="\x3c/tr\x3e"+"\x3c/table\x3e"+"\x3c/td\x3e"+"\x3c/tr\x3e"+"\x3c/table\x3e";return html}
function getButtonFontIconHTML(buttonLabel){var buttonFontIconHTML="";if(buttonLabel==="button.yes")buttonFontIconHTML='\x3ci class\x3d"fa fa-thumbs-o-up fa-lg"\x3e\x3c/i\x3e';else if(buttonLabel==="button.ok")buttonFontIconHTML='\x3ci class\x3d"fa fa-check-square-o fa-lg"\x3e\x3c/i\x3e';else if(buttonLabel==="button.no")buttonFontIconHTML='\x3ci class\x3d"fa fa-thumbs-o-down fa-lg"\x3e\x3c/i\x3e';else if(buttonLabel==="button.cancel")buttonFontIconHTML='\x3ci class\x3d"fa fa-close fa-lg"\x3e\x3c/i\x3e';
else if(buttonLabel==="button.continue")buttonFontIconHTML='\x3ci class\x3d"fa fa-caret-square-o-right fa-lg"\x3e\x3c/i\x3e';else if(buttonLabel==="button.save")buttonFontIconHTML='\x3ci class\x3d"fa fa-save fa-lg"\x3e\x3c/i\x3e';return buttonFontIconHTML}
function getWindowDiv(extraInfo,width,top,backgroundStyle,windowId){if(extraInfo!=null)width=width+50;var divId=MESSAGE_WINDOW_ID;if(windowId)divId=windowId;closeMessageWindow(divId);var windowWidth=getWindowWidth();if(width>windowWidth-50)width=windowWidth-50;var div=document.getElementById(divId);if(div==null){div=document.createElement("DIV");div.id=divId;document.body.appendChild(div)}if(backgroundStyle==null)backgroundStyle="";div.className="messageBox "+backgroundStyle;div.style.display="block";
div.style.width=""+width+"px";div.style.zIndex=1E6;div.style.position="absolute";if(document.forms[0]!=null){div.style.top=top+$(document.forms[0]).scrollTop()+"px";div.style.left=parseInt(windowWidth)/2+parseInt($(document.forms[0]).scrollLeft())-parseInt(width)/2+"px"}else{div.style.top=top+"px";div.style.left=parseInt(windowWidth)/2-parseInt(width)/2+"px"}return div}
function incrementProgressMeter(){var lastCell=getProgressMeterCell(0);if(lastCell!=null){lastCell.style.backgroundColor="#FFFFFF";progressMeterCellIndex++;if(progressMeterCellIndex>PROGRESS_METER_CELLS)progressMeterCellIndex=1;for(var i=0;i<PROGRESS_METER_ACTIVE_CELLS;i++){var fadeRatio=1-i/PROGRESS_METER_ACTIVE_CELLS;getProgressMeterCell(i).style.backgroundColor=fadeHex(progressMeterColor,16777215,fadeRatio)}if(progressMeterRunning)window.setTimeout(function(){incrementProgressMeter()},PROGRESS_METER_WAIT)}}
function isErrorPopup(){var isErrorPopup=false;var messageWindow=$("#"+MESSAGE_WINDOW_ID+"[class*\x3d'errorBackground']");if(messageWindow&&messageWindow.css("display")=="block")isErrorPopup=true;return isErrorPopup}
function rgbConvert(str){str=str.replace(/rgb\(|\)/g,"").split(",");str[0]=parseInt(str[0],10).toString(16).toLowerCase();str[1]=parseInt(str[1],10).toString(16).toLowerCase();str[2]=parseInt(str[2],10).toString(16).toLowerCase();str[0]=str[0].length==1?"0"+str[0]:str[0];str[1]=str[1].length==1?"0"+str[1]:str[1];str[2]=str[2].length==1?"0"+str[2]:str[2];return"0x"+str.join("")}
function setDetailButtonSet(){var saveButton=$("button[name\x3d'saveButton']");if(saveButton&&!progressMeterRunning)saveButton.prop("disabled",false);else saveButton.prop("disabled",true);var cancelButton=$("button[name\x3d'closeButton']");if(cancelButton&&!progressMeterRunning)cancelButton.prop("disabled",false);else cancelButton.prop("disabled",true)}
function showAlertWindow(messageText,isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action){showPromptWindowExt(messageText,"alertBackground",'\x3ci class\x3d"fa fa-exclamation-triangle fa-4x warningColor" /\x3e',isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action)}
function showMessageWindow(messageText,error,isPopup,width,extraInfo,extraInfoHeight){var top=50;if(isPopup)top=25;var div=getWindowDiv(extraInfo,width,top,error?"errorBackground":"successBackground");div.innerHTML=getMessageWindowHTML(messageText,error,extraInfo,extraInfoHeight,width);$("button[name\x3d'closeButton']").blur();setTimeout(function(){$("div.messageText").focus()},0);$("html, body").scrollTop($(div).offset().top)}
function showPlainMessageWindow(messageText,isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action){showPromptWindowExt(messageText,"","",isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action)}
function showPromptWindow(messageText,isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action,extraInfo){showPromptWindowExt(messageText,"alertBackground",'\x3ci class\x3d"fa fa-question-circle fa-4x warningColor" /\x3e',isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action,extraInfo)}
function showPromptWindowExt(messageText,background,image,isPopup,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action,extraInfo){if(EmbeddedPopup.popupManager.openedCoversForMessageWindow<=0){var windowScrollY=$(window).scrollTop();if(width==null)width=324;var top=175;if(isPopup)top=75;EmbeddedPopup.popupManager.openCover();EmbeddedPopup.popupManager.openedCoversForMessageWindow=1;var div=getWindowDiv(extraInfo,width,top,background);if(div!=null){div.innerHTML=getPromptWindowHTML(messageText,
image,width,button1Label,button1Action,button2Label,button2Action,button3Label,button3Action,extraInfo);document.getElementById("msgbutton1").focus()}else;$(window).scrollTop(windowScrollY);verticallyCenterDiv(div);$(window).on("scroll",function(){verticallyCenterDiv(div)})}}
function startProgressMeter(messageText,isPopup){progressMeterColor=$("#c2colorRef").css("color");if(!isInternetExplorer())progressMeterColor=rgbConvert(progressMeterColor);else progressMeterColor="0x"+progressMeterColor.substring(1);var width=400;var top=50;if(isPopup)top=25;var div=getWindowDiv(null,width,top,null,PROGRESS_METER_ID);div.innerHTML=getProgressMeterHTML(messageText);progressMeterRunning=true;setDetailButtonSet();incrementProgressMeter()}
function stopProgressMeter(){closeMessageWindow(PROGRESS_METER_ID)}function verticallyCenterDiv(div){var windowScrollY=$(window).scrollTop();$(div).offset({left:$(div).offset().left,top:(getWindowHeight()-$(div).height())/2+windowScrollY})};